// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeviathanerProgramming.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428222822_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LeviathanerProgramming.Models.Lenguaje", b =>
                {
                    b.Property<int>("IdLenguaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLenguaje"));

                    b.Property<string>("NombreLenguaje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdLenguaje");

                    b.ToTable("Lenguaje", (string)null);
                });

            modelBuilder.Entity("LeviathanerProgramming.Models.NivelDificultad", b =>
                {
                    b.Property<int>("IdNivelDificultad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNivelDificultad"));

                    b.Property<string>("NombreDificultad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdNivelDificultad");

                    b.ToTable("NivelDificultad", (string)null);
                });

            modelBuilder.Entity("LeviathanerProgramming.Models.Post", b =>
                {
                    b.Property<int>("IdPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPost"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nivel_Dificiltad_Id")
                        .HasColumnType("int");

                    b.Property<int>("Road_Map_Id")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdPost");

                    b.HasIndex("Nivel_Dificiltad_Id");

                    b.HasIndex("Road_Map_Id");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("LeviathanerProgramming.Models.RoadMap", b =>
                {
                    b.Property<int>("IdRoadMap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRoadMap"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Lenguaje_Programacion_Id")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdRoadMap");

                    b.HasIndex("Lenguaje_Programacion_Id");

                    b.ToTable("RoadMap", (string)null);
                });

            modelBuilder.Entity("LeviathanerProgramming.Models.TipoRutaAprendizaje", b =>
                {
                    b.Property<int>("IdRutaAprendizaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRutaAprendizaje"));

                    b.Property<string>("NombreTipoAprenidzaje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Road_Map_Id")
                        .HasColumnType("int");

                    b.HasKey("IdRutaAprendizaje");

                    b.HasIndex("Road_Map_Id");

                    b.ToTable("TipoRutaAprendizaje", (string)null);
                });

            modelBuilder.Entity("LeviathanerProgramming.Models.Post", b =>
                {
                    b.HasOne("LeviathanerProgramming.Models.NivelDificultad", "ListaDificultad")
                        .WithMany()
                        .HasForeignKey("Nivel_Dificiltad_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeviathanerProgramming.Models.RoadMap", "ListaRoadMap")
                        .WithMany()
                        .HasForeignKey("Road_Map_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaDificultad");

                    b.Navigation("ListaRoadMap");
                });

            modelBuilder.Entity("LeviathanerProgramming.Models.RoadMap", b =>
                {
                    b.HasOne("LeviathanerProgramming.Models.Lenguaje", "ListaLenguaje")
                        .WithMany()
                        .HasForeignKey("Lenguaje_Programacion_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaLenguaje");
                });

            modelBuilder.Entity("LeviathanerProgramming.Models.TipoRutaAprendizaje", b =>
                {
                    b.HasOne("LeviathanerProgramming.Models.RoadMap", "ListaRoadMap")
                        .WithMany()
                        .HasForeignKey("Road_Map_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaRoadMap");
                });
#pragma warning restore 612, 618
        }
    }
}
